"""Phase-2 calibration (PLAN-V2 §7): real per-image measurements on the
Committed 20 -> data/baselines/metrics.json. All values measured, none
estimated. Prints the per-image CER table + provisional-gate verdict."""
import datetime
import json
import os
import sys
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "app"))
sys.path.insert(0, os.path.join(ROOT, "tests"))
sys.path.insert(0, os.path.join(ROOT, "tests", "model"))

from ocr_engine import ocr_bytes  # noqa: E402
from cer import field_cer  # noqa: E402
from degrade import to_array, from_array, blur_heavy  # noqa: E402
from conftest import load_golden  # noqa: E402

GATE_CLEAN = 0.05
GATE_BLUR = 0.25
OUT = os.path.join(ROOT, "data", "baselines", "metrics.json")


def main():
    golden = load_golden()
    rows = []
    t_sum = 0.0
    for item in golden:
        t0 = time.perf_counter()
        r = ocr_bytes(item["bytes"])
        t_clean = time.perf_counter() - t0
        t_sum += t_clean
        img = to_array(item["bytes"])
        t0 = time.perf_counter()
        rb = ocr_bytes(from_array(blur_heavy(img)))
        t_sum += time.perf_counter() - t0
        c_clean, _ = field_cer(item["gt"], r["text"])
        c_blur, _ = field_cer(item["gt"], rb["text"])
        rows.append(
            {
                "file": item["file"],
                "cer_clean": round(c_clean, 4),
                "cer_blur": round(c_blur, 4),
                "conf": r["confidence"],
            }
        )
        print(
            f"{item['file']}  clean={c_clean:.4f}  blur={c_blur:.4f}  conf={r['confidence']:.3f}  t={t_clean:.2f}s"
        )

    clean = [r["cer_clean"] for r in rows]
    blur = [r["cer_blur"] for r in rows]
    metrics = {
        "provenance": (
            "QUACKO V2 Phase-2 calibration. Real Tesseract 5 over the Committed 20 "
            "(SHA256-verified), local run 2026-09-14. Generated by scripts/calibrate.py "
            "— every value measured, none estimated."
        ),
        "generated": datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds"),
        "receipts": len(rows),
        "avg_ocr_s": round(t_sum / (2 * len(rows)), 3),
        "clean_cer_mean": round(sum(clean) / len(clean), 4),
        "blur_cer_mean": round(sum(blur) / len(blur), 4),
        "by_receipt": rows,
    }
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump(metrics, fh, indent=2)
    print(f"\nmean clean CER = {metrics['clean_cer_mean']:.4f} (gate {GATE_CLEAN})")
    print(f"mean blur  CER = {metrics['blur_cer_mean']:.4f} (gate {GATE_BLUR})")
    print(f"avg OCR time   = {metrics['avg_ocr_s']} s")
    bad_clean = [r["file"] for r in rows if r["cer_clean"] >= GATE_CLEAN]
    bad_blur = [r["file"] for r in rows if r["cer_blur"] >= GATE_BLUR]
    if bad_clean:
        print(f"MQ-T1 gate misses (clean): {bad_clean}")
    else:
        print("MQ-T1: all 20 under clean gate")
    if bad_blur:
        print(f"MQ-T2 gate misses (blur): {bad_blur}")
    else:
        print("MQ-T2: all 20 under blur gate")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
